apiVersion: constraints.gatekeeper.sh/v1beta1
kind: ServiceLabels
metadata:
  name: requiredservicelabels
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Service"]
  parameters:
    annotations: 
      - "loadbalancernetwork"
