apiVersion: constraints.gatekeeper.sh/v1beta1
kind: LoadBalancerLabels
metadata:
  name: requiredlabels-team
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Namespace"]
  # parameters:
  #   labels: 
  #     - "team"
