# Demo use only
---
apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: servicelabels
spec:
  crd:
    spec:
      names:
        kind: ServiceLabels
        listKind: ServiceLabelsList
        plural: servicelabels
        singular: servicelabels
      validation:
        openAPIV3Schema:
          properties:
            annotations:
              type: array
              items: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
         package servicelabels

         violation[{"msg": msg, "details": {}}] {
           provided := {label | input.review.object.metadata.annotations[label]}
           required := {label | label := input.parameters.annotations[_]}
           missing := required - provided
           count(missing) > 0
           msg := sprintf("\n\nDENIED. \nReason: Our org policy mandates the following annotations: %v\nYou must provide these annotations: %v", [required, missing])
         }

         violation[{"msg": msg, "details": {}}] {
           network := input.review.object.metadata.annotations.loadbalancernetwork
           not network == "private"
           msg := sprintf("\n\nDENIED. \nReason: Our org policy mandates a private network for load balancers")
         }
---
