# Demo use only
---
apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: servicelabels
spec:
  crd:
    spec:
      names:
        kind: ServiceLabels
        listKind: ServiceLabelsList
        plural: servicelabels
        singular: servicelabels
      validation:
        openAPIV3Schema:
          properties:
            annotations:
              type: array
              items: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
         package servicelabels

         violation[{"msg": msg}] {
           input.review.object.kind == "Service"
           input.review.object.spec.type == "LoadBalancer"
           not input.review.object.metadata.annotations.loadbalancernetwork
           msg := "Error you must use a loadbalancernetwork annotation."
         }

         violation[{"msg": msg}] {
           not input.review.object.metadata.annotations.loadbalancernetwork == "private"
           msg := "The loadbalancernetwork must be private."
         }

         violation[{"msg": msg}] {
           not input.review.object.spec.loadBalancerIP
           msg := "The loadBalancerIP must be provided."
         }

---
